AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-app

  Sample SAM Template for customer-app
Parameters:
  TargetSnsTopicArn:
    Type: String
    Default: 'arn:aws:sns:eu-west-1:133548157508:food-delivery'
    Description: The SNS topic ARN which the Lambda will publish events to.
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CustomersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: LambdaPublishToSns
          Effect: Allow
          Action:
            - sns:Publish
          Resource: !Ref TargetSnsTopicArn
      Environment:
        Variables:
          TargetSnsTopicArn: !Ref TargetSnsTopicArn
      Events:
        PostCustomer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /customer
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CutomerApi:
    Description: "API Gateway endpoint URL for Prod stage for Customer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customer/"
  CustomersFunction:
    Description: "Customers Lambda Function ARN"
    Value: !GetAtt CustomersFunction.Arn
